auto_light_automations: 

  input_boolean:
    presence_simulation:
      name: Имитация присутствия
      icon: mdi:home-account

  automation:
    - id: imitacia_pricutstvia_vkluchit_svet
      alias: Имитация присутствия включить свет
      triggers:
        - trigger: sun
          event: sunset

        - trigger: time
          at: "14:00:00"
      conditions:
        - condition: state
          entity_id: input_boolean.presence_simulation
          state: 'on'
      actions:
        - parallel:
            - sequence:
              - delay: 
                  minutes: >-
                    {{ 
                      range(states('input_number. min_minutes_presence_simulation_light_switch'), 
                      'input_number. max_minutes_presence_simulation_light_switch') | random 
                    }}
              - action: switch.turn_on
                entity_id: switch.switch_kitchen_hall_left

            - sequence:
              - delay: 
                  minutes: >-
                    {{ 
                      range(states('input_number. min_minutes_presence_simulation_light_switch'), 
                      'input_number. max_minutes_presence_simulation_light_switch') | random 
                    }}
              - action: light.turn_on
                entity_id: light.lamp_kitchen

            - sequence:
              - delay: 
                  minutes: >-
                    {{ 
                      range(states('input_number. min_minutes_presence_simulation_light_switch'), 
                      'input_number. max_minutes_presence_simulation_light_switch') | random 
                    }}
              - action: light.turn_on
                entity_id: light.lamp_big_bedroom_marina_white
                data:
                  brightness: 254
                  color_temp: 4300

            - sequence:
              - delay: 
                  minutes: >-
                    {{ 
                      range(states('input_number. min_minutes_presence_simulation_light_switch'), 
                      'input_number. max_minutes_presence_simulation_light_switch') | random 
                    }}
              - action: light.turn_on
                entity_id: light.lamp_bedroom_andrey_white
                data:
                  brightness: 254
                  color_temp: 4300
#============================================================
    - id: imitacia_pricutstvia_vykluchit_svet
      alias: Имитация присутствия выключить свет
      triggers:
        - trigger: time
          at: "21:00:00"
      conditions:
        - condition: state
          entity_id: input_boolean.presence_simulation
          state: 'on'
      actions:
        - parallel:
            - sequence:
              - delay: 
                  minutes: >-
                    {{ 
                      range(states('input_number. min_minutes_presence_simulation_light_switch'), 
                      'input_number. max_minutes_presence_simulation_light_switch') | random 
                    }}
              - action: switch.turn_off
                entity_id: switch.switch_kitchen_hall_left

            - sequence:
              - delay: 
                  minutes: >-
                    {{ 
                      range(states('input_number. min_minutes_presence_simulation_light_switch'), 
                      'input_number. max_minutes_presence_simulation_light_switch') | random 
                    }}
              - action: light.turn_off
                entity_id: light.lamp_kitchen

            - sequence:
              - delay: 
                  minutes: >-
                    {{ 
                      range(states('input_number. min_minutes_presence_simulation_light_switch'), 
                      'input_number. max_minutes_presence_simulation_light_switch') | random 
                    }}
              - action: light.turn_off
                entity_id: light.lamp_big_bedroom_marina_white

            - sequence:
              - delay: 
                  minutes: >-
                    {{ 
                      range(states('input_number. min_minutes_presence_simulation_light_switch'), 
                      'input_number. max_minutes_presence_simulation_light_switch') | random 
                    }}
              - action: light.turn_off
                entity_id: light.lamp_bedroom_andrey_white