toilet_automations:
 
  script:
    light_turn_on_depending_on_daytime_toulet:
      sequence:
          #Включить свет
        - action: switch.turn_on
          #Если ночь, включить подсветку, если день включить основной свет
          data_template:
            entity_id: >
              {% if is_state("binary_sensor.is_night",  "on") %}
              switch.backlight_toilet
              {% else %}
              switch.switch_toilet_up
              {% endif %} 
  timer:
    toilet_light_off_timer:
      name: Таймер на выключение света в туалете
      duration: "00:00:05"
      restore: true

  template:
    binary_sensor:
      - name: 'motion_toilet'
        state: >
          {{not is_state("sensor.presence_toilet_presence_event", "leave")}}
        device_class: motion
        unique_id: presence_to_motion_toilet
        
  automation:
    - id: toilet_light_on_by_presence_sensor
      alias: Включить свет по датчику присутствия
      triggers:
        - trigger: state
          entity_id: binary_sensor.motion_toilet
          to: "on"
      conditions:
          #Если свет выключен
        - condition: template
          #Если ночь, то проверить подсветку, если день - основной свет
          value_template: > 
            {% if is_state("binary_sensor.is_night",  "on") %}
            {{ is_state ("switch.backlight_toilet", "off") }}
            {% else %}
            {{ is_state ("switch.switch_toilet_up", "off") }}
            {% endif %} 
          # если дверь открыта
        - condition: state
          entity_id: binary_sensor.door_toilet_contact
          state: "on"
      actions:
          #Запустить скрипт включающий свет разной интенсивности в зависимости от времени суток
        - action: script.turn_on
          entity_id: script.light_turn_on_depending_on_daytime_toulet
#===================================================
    - id: toilet_light_off_by_presence_sensor
      alias: Выключить свет по датчику присутствия
      triggers:
        - trigger: state
          entity_id: binary_sensor.motion_toilet
          to: "off"
      actions:
        - action: switch.turn_off
          entity_id: 
            - switch.backlight_toilet
            - switch.switch_toilet_up
#============================================= 
    - id: toilet_manual_light_on
      alias: Включение света в туалете вручную
      triggers:
          #свет включается
        - trigger: state
          entity_id: switch.switch_toilet_up
          to: "on"
      conditions:
          #если движения не обнаружено
        - condition: state
          entity_id: binary_sensor.motion_toilet
          state: "off"
          #если дверь закрыта
        - condition: state
          entity_id: binary_sensor.door_toilet_contact
          state: "off"
      actions:
          #запустить таймер на выключение света
        - action: timer.start
          entity_id: timer.toilet_light_off_timer
#============================================= 
    - id: toilet_manual_light_off
      alias: Выключение света в туалете вручную
      triggers:
          #свет выключается
        - trigger: state
          entity_id: switch.switch_toilet_up
          to: "off"
      action:
          #отменить все таймеры
        - action: timer.cancel
          entity_id: timer.toilet_light_off_timer
#============================================= 
    - id: toilet_fan
      alias: Вентиляции в туалете
      triggers:
         #Если нажата нижняя кнопка выключателя
        - trigger: state
          id: manual_on_off
          entity_id: sensor.switch_toilet_action
          to: "single_down"
         #Если свет включен в течении нескольких минут
        - trigger: state
          id: fan_on_when_light_on_for_several_minutes
          entity_id: switch.switch_toilet_up
          to: "on"
          for: "00:05:00"
         #Если свет выключен в течении нескольких минут
        - trigger: state
          id: fan_off_when_light_off_for_several_minutes
          entity_id: switch.switch_toilet_up
          to: "off"
          for: "00:02:00"
      actions:
        choose:
        - conditions:
            #Если сработал триггер по нажатию на выключатель
            condition: trigger
            id: "manual_on_off"
          sequence:
            #Перекючить вентиляцию
            action: switch.toggle
            entity_id: switch.fan_toilet
        - conditions:
              #Если сработал триггер по включенному несколько минут свету
            - condition: trigger
              id: "fan_on_when_light_on_for_several_minutes"
              #Если вентиляция выключена
            - condition: state
              entity_id: switch.fan_toilet
              state: "off"
          sequence:
            #Включить вентиляцию
            action: switch.turn_on
            entity_id: switch.fan_toilet
        - conditions:
              #Если сработал триггер по выключенному несколько минут свету
            - condition: trigger
              id: "fan_off_when_light_off_for_several_minutes"
              #Если вентиляция включена
            - condition: state
              entity_id: switch.fan_toilet
              state: "on"
          sequence:
            #Выключить вентиляцию
            action: switch.turn_off
            entity_id: switch.fan_toilet